name: Run Tests

on: push
jobs:
  go-tests:
    name: Run Go Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - uses: autero1/action-terraform@v0.1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          terraform_version: 1.0.11
      - name: install wg and yggdrasil and add peers
        run: |
          sudo apt-get update
          sudo apt-get install -y wireguard
          sudo apt-get install dirmngr
          gpg --fetch-keys https://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/key.txt
          gpg --export 569130E8CA20FBC4CB3FDE555898470A764B32C9 | sudo apt-key add -
          echo 'deb http://neilalexander.s3.dualstack.eu-west-2.amazonaws.com/deb/ debian yggdrasil' | sudo tee /etc/apt/sources.list.d/yggdrasil.list
          sudo apt-get update
          sudo apt-get install yggdrasil
          sudo systemctl enable yggdrasil
          sudo  sed -i -- 's/Peers\: \[\]/Peers\: \[\n\ttcp\:\/\/51\.15\.204\.214\:12345\n\ttcp\:\/\/94\.130\.203\.208\:5999\n\]/g'  /etc/yggdrasil.conf
          sudo systemctl start yggdrasil
      - name: Download Go Modules
        working-directory: tests
        run: |
          go mod download
          go get gotest.tools/gotestsum
          go mod tidy
      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        with:
          gotestsum_version: 0.4.1
      - name: Run Go Tests
        env:
          MNEMONICS: ${{ secrets.MNEMONICS }}
          NETWORK: ${{ secrets.NETWORK }}
          KEY_TYPE: ${{ secrets.KEY_TYPE }}
        working-directory: tests
        run: gotestsum --format testname

