name: Lint
on:
  pull_request:
    paths-ignore:
      - "README.md"
  push:
    paths-ignore:
      - "README.md"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18"
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3.0.2
        with:
          submodules: "true"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          args: --timeout 3m --verbose

      - name: staticcheck
        uses: dominikh/staticcheck-action@v1.2.0

      - name: gofmt
        uses: Jerome1337/gofmt-action@v1.0.4
        with:
          gofmt-flags: "-l -d"
